//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace TodoProjects4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodoObject
    {
        public int Id { get; set; }
        public int TotalScore { get; set; }
        public Nullable<int> q1 { get; set; }
        public Nullable<int> q2 { get; set; }
        public Nullable<int> q3 { get; set; }
        public Nullable<int> q4 { get; set; }
        public string note { get; set; }
        [DisplayFormat(DataFormatString ="{0:dd-MMM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> deadLine { get; set; }
        public string todo { get; set; }

        public override string ToString()
        {
            String ans = "{\t\n todo: " + todo + ",\n\t id: " + Id + ",\n\t TotalScore: " + TotalScore + ",\n\t" + ",\n\t q1: " + q1 + ",\n\t q2: " + q2 + ",\n\t q3: " + q3 + ",\n\t q4: " + q4 + ",\n}";
            return ans;
        }
    }
}
